version: "3.6"

networks:
  splunknet:
    driver: bridge
    attachable: true

services:
  uf1:
    networks:
      splunknet:
        aliases:
          - uf1
    image: ${UF_IMAGE:-dodex/uforward2:latest}
    hostname: uf1
    container_name: uf1
    environment:
      - SPLUNK_STANDALONE_URL=so1
      - SPLUNK_INDEX=dev
    volumes:
       - /var/lib/docker/containers:/host/containers:ro
       - /var/run/docker.sock:/var/run/docker.sock:ro
    ports:
      - 8089

  so1:
    networks:
      splunknet:
        aliases:
          - so1
    image: ${SPLUNK_IMAGE:-splunk/splunk:latest}
    hostname: so1
    container_name: so1
    environment:
      - SPLUNK_START_ARGS= --accept-license
      - SPLUNK_STANDALONE_URL=so1
      - SPLUNK_PASSWORD=admin!@#
    ports:
      - 8000:8000
      - 8088:8088
      - 8089
      - 9997

  nginx:
    networks:
      splunknet:
        aliases:
          - nginx
    image: ${SPLUNK_IMAGE:-nginx}
    hostname: nginx
    container_name: nginx
    logging:
        driver: splunk
        options:
            splunk-url: http://172.23.0.3:8088
            splunk-token: 38fd07e4-fe12-4d36-9e15-b0a3df561b1a
            splunk-index: splunk_index
            splunk-insecureskipverify: "true"
            splunk-format: "json"
            tag: "{{.Name}}/{{.ID}}"
    ports:
      - 80:80