version: '3'

networks:
  splunknet:

services:
  uf1:
    image: dodex/uforward:latest
    hostname: uf1
    container_name: uf1
    networks:
      - splunknet
    environment:
      - SPLUNK_STANDALONE_URL=so1
      - SPLUNK_INDEX=dev
    volumes:
       - /var/lib/docker/containers:/host/containers:ro
       - /var/run/docker.sock:/var/run/docker.sock:ro

  so1:
    image: splunk/splunk
    hostname: so1
    container_name: so1
    networks:
      - splunknet
    environment:
      - SPLUNK_START_ARGS= --accept-license
      - SPLUNK_STANDALONE_URL=so1
      - SPLUNK_PASSWORD=admin!@#
    volumes:
      - ./so1-var:/opt/splunk/var
      - ./so1-etc:/opt/splunk/etc
    ports:
      - 8000:8000
      - 8088:8088
      - 8089
      - 9997

  nginx1:
    image: nginx
    hostname: nginx1
    container_name: nginx1
    networks:
      - splunknet
    logging:
        driver: splunk
        options:
            splunk-url: http://172.23.0.2:8088
            splunk-token: f16ff2ee-0773-43e3-9bbd-21f1bca57110
            splunk-index: splunk_index
            splunk-insecureskipverify: "true"
            splunk-format: "json"
            tag: "{{.Name}}/{{.ID}}"
    ports:
      - 80:80

  
  nginx2:
    image: nginx
    hostname: nginx2
    container_name: nginx2
    networks:
      - splunknet
    logging:
        driver: splunk
        options:
            splunk-url: http://172.23.0.2:8088
            splunk-token: f16ff2ee-0773-43e3-9bbd-21f1bca57110
            splunk-index: splunk_index
            splunk-insecureskipverify: "true"
            splunk-format: "json"
            tag: "{{.Name}}/{{.ID}}"
    ports:
      - 81:80

  nginx3:
    image: nginx
    hostname: nginx3
    container_name: nginx3
    networks:
      - splunknet
    logging:
        driver: splunk
        options:
            splunk-url: http://172.23.0.2:8088
            splunk-token: f16ff2ee-0773-43e3-9bbd-21f1bca57110
            splunk-index: splunk_index
            splunk-insecureskipverify: "true"
            splunk-format: "json"
            tag: "{{.Name}}/{{.ID}}"
    ports:
      - 81:80